1. Events Table

User interaction events captured during browsing sessions.

| Column Name   | Data Type   | Variable Type | Description                                   | Example Values                          | Notes |
|---------------|-------------|---------------|-----------------------------------------------|------------------------------------------|------|
| user_id       | Integer     | Categorical   | Unique identifier of the user                | 62, 113, 191 … 6912                      | Links to `users.id` |
| ga_session_id | Integer     | Categorical   | Unique Google Analytics session identifier   | 1, 2, 3 … 2689                           | Session-level tracking |
| country       | String      | Categorical   | Country code of the user                     | AE, AL, VN, XK, ZA                       | 109 distinct values |
| device        | String      | Categorical   | Device used to access the platform           | mobile, desktop, tablet                  | 3 categories |
| type          | String      | Categorical   | Type of user interaction event               | add_to_cart, begin_checkout, purchase    | Key behavioral variable |
| item_id       | Integer     | Categorical   | Identifier of the item related to the event  | 0,1,2 … 999                              | Links to `items.id` |
| date          | Datetime    | Time Series   | Timestamp when the event occurred            | 2020-11-29 12:05:14                      | Used for temporal analysis |


2. Items Table

Product catalog information.

| Column Name   | Data Type | Variable Type | Description                           | Example Values                                      | Notes |
|---------------|-----------|---------------|---------------------------------------|----------------------------------------------------|------|
| id            | Integer   | Categorical   | Unique product identifier             | 0,1,2 … 999                                        | Primary key |
| name          | String    | Text          | Product name                          | Google Women's Kirkland Pullover                   | |
| brand         | String    | Categorical   | Product brand                         | Google, Android, YouTube, Google Cloud             | 5 brands |
| variant       | String    | Categorical   | Product variant (size, color, etc.)   | 12M, 12/18 MONTHS, No options available             | 45 variants |
| category      | String    | Categorical   | Product category                      | Apparel, Bags, Accessories, Eco-Friendly           | 21 categories |
| price_in_usd  | Integer   | Numerical     | Product price in USD                  | 1 – 313                                            | Used for revenue analysis |


3. Users Table

User-level information and lifetime value metrics.

| Column Name | Data Type | Variable Type | Description                                   | Example Values | Notes |
|-------------|-----------|---------------|-----------------------------------------------|---------------|------|
| id          | Integer   | Categorical   | Unique user identifier                       | 62,113,191…6912 | Primary key |
| ltv         | Integer   | Numerical     | Lifetime value generated by the user (USD)   | 40, 85, 523, 1200 | Key business KPI |
| date        | Datetime  | Time Series   | Date when the user account was created       | 2020-05-23 08:34:20 | Used for cohort analysis |
